### ISSUE TITLE
Add translation for ar_IQ locale

### ISSUE THREAD

**Issue by jnugent** [lepidus/authorsHistory#2]
A client has kindly provided a translation for the ar_IQ locale for the plugin.  Here is a file for stable-3_3_0.

[locale.po.gz](https://github.com/user-attachments/files/16015290/locale.po.gz)

**Comment by iudizm** [comment]
Thank you very much @jnugent !

Integrated the locale for `stable-3_3_0`

I also [added the translation as the general Arab locale `ar` for the 3.4 version](https://github.com/lepidus/authorsHistory/commit/cab917cac13c76f50b3f70b6dc1f501203ddeef1), as some online tools pointed it to be in Modern Standard Arabic already

does that sound good?

**Comment by jnugent** [comment]
thanks!  That's perfect!
